// <auto-generated />
namespace Emsys.DataAccesLayer.Core
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _AgregoEvento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_AgregoEvento));
        
        string IMigrationMetadata.Id
        {
            get { return "201609090128413__AgregoEvento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
